jqassistant:
  plugins:
    - group-id: de.kontext-e.jqassistant.plugin
      artifact-id: jqassistant.plugin.pmd
      version: 2.1.0
  scan:
    include:
      files:
        - ${project.build.directory}/pmd.xml
  analyze:
    groups:
      - biojava:Default